spring:
  application:
    name: food-diary
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftlh
    charset: UTF-8
    content-type: text/html
    cache: false
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    settings:
      localized_lookup: false
      number_format: computer
      datetime_format: iso
      date_format: iso
      time_format: iso

provider:
  open-food-facts:
    base-url: https://world.openfoodfacts.org
    enabled: ${OPEN_FOOD_FACTS_ENABLED:false}
  usda:
    base-url: https://api.nal.usda.gov
    api-key: ${FOOD_DATA_SERVICE_API_KEY:}
    enabled: ${USDA_ENABLED:true}
  my-memory-translate:
    base-url: https://api.mymemory.translated.net

app:
  nutrition-lookup-cache-duration-days: 7
  admin:
    email: ${APP_ADMIN_EMAIL:}
    password: ${APP_ADMIN_PASSWORD:}
