create table roles (
    id bigint generated by default as identity,
    name varchar(50) not null,
    constraint pk_roles primary key (id),
    constraint uk_roles_name unique (name)
);

create table goals (
    id bigint generated by default as identity,
    name varchar(50) not null,
    calories_modifier numeric(5, 3) not null,
    proteins_ratio numeric(5, 4) not null,
    fats_ratio numeric(5, 4) not null,
    carbohydrates_ratio numeric(5, 4) not null,
    constraint pk_goals primary key (id),
    constraint uk_goals_name unique (name)
);

create table users (
    id bigint generated by default as identity,
    email varchar(254) not null,
    password_hash varchar(255) not null,
    enabled boolean not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_users primary key (id),
    constraint uk_users_email unique (email)
);

create table user_roles (
    user_id bigint not null,
    role_id bigint not null,
    constraint pk_user_roles primary key (user_id, role_id),
    constraint uk_user_roles_user_id_role_id unique (user_id, role_id),
    constraint fk_user_roles_user foreign key (user_id) references users (id),
    constraint fk_user_roles_role foreign key (role_id) references roles (id)
);

create table user_profiles (
    id bigint generated by default as identity,
    user_id bigint not null,
    gender varchar(32) not null,
    birth_date date not null,
    height_cm integer not null,
    weight_kg numeric(6, 2) not null,
    activity_level varchar(32) not null,
    goal_id bigint not null,
    constraint pk_user_profiles primary key (id),
    constraint uk_user_profiles_user_id unique (user_id),
    constraint fk_user_profiles_user foreign key (user_id) references users (id),
    constraint fk_user_profiles_goal foreign key (goal_id) references goals (id)
);

create table products (
    id bigint generated by default as identity,
    name varchar(255) not null,
    calories_per_100g numeric(10, 2) not null,
    proteins_per_100g numeric(10, 2) not null,
    fats_per_100g numeric(10, 2) not null,
    carbohydrates_per_100g numeric(10, 2) not null,
    owner_id bigint not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_products primary key (id),
    constraint fk_products_owner foreign key (owner_id) references users (id)
);

create table food_entries (
    id bigint generated by default as identity,
    entry_date date not null,
    meal_type varchar(32) not null,
    grams numeric(10, 2) not null,
    calories numeric(10, 2) not null,
    proteins numeric(10, 2) not null,
    fats numeric(10, 2) not null,
    carbohydrates numeric(10, 2) not null,
    user_id bigint not null,
    product_id bigint not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_food_entries primary key (id),
    constraint fk_food_entries_user foreign key (user_id) references users (id),
    constraint fk_food_entries_product foreign key (product_id) references products (id)
);
